import '@testing-library/jest-dom/vitest'
import { vi } from 'vitest'
import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'

vi.mock('sonner', () => ({
  Toaster: () => null,
  toast: {
    error: vi.fn(),
    success: vi.fn(),
    info: vi.fn(),
    warning: vi.fn(),
  },
}))

void i18next
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: {
          app: { title: 'Scan2Text' },
          panels: { dropZone: 'Drop Zone', queue: 'Queue', preview: 'Preview' },
          status: { ready: 'Ready' },
          actions: { toggleTheme: 'Toggle theme', toggleLanguage: 'Toggle language', langTooltipEn: 'Switch to Bahasa', langTooltipId: 'Switch to English', shareTooltip: 'Share app link' },
          dropzone: {
            hint: 'PNG · JPG · WEBP · PDF — max 50MB per file · max 10 files per batch',
            clickLabel: 'Click or drag files here',
            dropLabel: 'Drop files here',
            maxFilesWarning: 'Max 10 files per batch — extra files were skipped.',
          },
          errors: {
            unsupportedFileType: 'Unsupported file type. Allowed: PNG, JPG, JPEG, WEBP, PDF',
            fileTooLarge: 'File exceeds 50MB limit',
            uploadFailed: 'Upload failed',
            batchSkipped: '{{total}} files were skipped: {{unsupported}} unsupported type(s), {{tooLarge}} too large.',
            allInvalid: 'All selected files are unsupported or too large.',
          },
          preview: {
            empty: 'Select a job to preview',
            loading: 'Processing your file...',
            error: 'Processing failed. Please try again.',
            retry: 'Retry',
          },
          queue: {
            empty: 'No files in queue',
            emptyFriendly: ' Nothing here yet. Drop something tasty!',
            remove: 'Remove',
            retry: 'Retry',
            status: {
              pending: 'Pending',
              uploading: 'Uploading',
              processing: 'Processing',
              completed: 'Completed',
              failed: 'Failed',
            },
          },
          bottomBar: {
            workerLabel: 'Worker: {{status}}',
            ramUsage: 'RAM: {{percent}}%',
            version: 'v0.1.0-demo',
          },
          settings: {
            title: 'Settings',
            general: 'General',
            processing: 'Processing (Backend Required)',
            outputDir: '\ud83d\udd12 Output Directory',
            maxPdfPages: '\ud83d\udd12 Max PDF Pages',
            cpuThreads: '\ud83d\udd12 CPU Threads',
            reopenWelcome: 'Re-open Welcome Screen',
            save: 'Save',
            close: 'Close',
            saved: 'Settings saved',
            saveFailed: 'Failed to save settings.',
            loadFailed: 'Failed to load settings.',
            validationPages: 'Max PDF Pages must be at least 1.',
            validationThreads: 'CPU Threads cannot be negative.',
            autoHint: '0 = auto',
          },
          topbar: {
            logoAlt: 'Scan2Text logo',
            brandAlt: 'Scan2Text',
            demoBadge: 'DEMO',
          },
          welcome: {
            title: 'Welcome to Scan2Text',
            bullet1: 'Works fully offline; your files never leave this PC.',
            bullet2: 'No accounts, no telemetry, no document content or file names in logs.',
            bullet3: 'Big or dense files can take several minutes; the app stays responsive.',
            bullet4: 'Output is best-effort Markdown — always double-check important numbers.',
            dontShowAgain: "Don't show this again",
            close: 'Get Started',
          },
          feedback: {
            tooltip: 'Send feedback',
            title: 'Send Feedback',
            messageLabel: 'Your feedback',
            messagePlaceholder: 'Tell us what you think...',
            contactLabel: 'Email (optional)',
            contactPlaceholder: 'you@example.com',
            submit: 'Send',
            success: 'Feedback saved!',
            pendingToast: 'You have pending feedback to send.',
            pendingAction: 'Send now',
            formUrl: 'https://placeholder.local/feedback',
          },
          downloader: {
            title: 'Downloading AI Engine',
            description: 'Please wait while we prepare the offline AI model...',
            progress: '{{downloaded}} of {{total}}',
            cancel: 'Cancel',
            restart: 'Restart Download',
            failed: 'Download failed or cancelled.',
            verifying: 'Verifying file integrity...',
          },
        },
      },
      id: {
        translation: {
          app: { title: 'Scan2Text' },
          panels: { dropZone: 'Zona Jatuh', queue: 'Antrian', preview: 'Pratinjau' },
          status: { ready: 'Siap' },
          actions: { toggleTheme: 'Ubah tema', toggleLanguage: 'Ubah bahasa', langTooltipEn: 'Beralih ke Bahasa Indonesia', langTooltipId: 'Beralih ke Bahasa Inggris', shareTooltip: 'Bagikan tautan aplikasi' },
          dropzone: {
            hint: 'PNG · JPG · WEBP · PDF — maks 50MB per file · maks 10 file per batch',
            clickLabel: 'Klik atau seret file ke sini',
            dropLabel: 'Lepaskan file di sini',
            maxFilesWarning: 'Maksimal 10 file per batch — file tambahan dilewati.',
          },
          errors: {
            unsupportedFileType: 'Tipe file tidak didukung. Yang didukung: PNG, JPG, JPEG, WEBP, PDF',
            fileTooLarge: 'Ukuran file melebihi batas 50MB',
            uploadFailed: 'Gagal mengunggah',
            batchSkipped: '{{total}} file dilewati: {{unsupported}} tipe tidak didukung, {{tooLarge}} terlalu besar.',
            allInvalid: 'Semua file yang dipilih tidak didukung atau terlalu besar.',
          },
          preview: {
            empty: 'Pilih pekerjaan untuk pratinjau',
            loading: 'Memproses file Anda...',
            error: 'Pemrosesan gagal. Silakan coba lagi.',
            retry: 'Coba Lagi',
          },
          queue: {
            empty: 'Tidak ada file dalam antrian',
            emptyFriendly: '🙈 Masih belum ada file tuh! Coba upload di atas!',
            remove: 'Hapus',
            retry: 'Ulangi',
            status: {
              pending: 'Menunggu',
              uploading: 'Mengunggah',
              processing: 'Memproses',
              completed: 'Selesai',
              failed: 'Gagal',
            },
          },
          bottomBar: {
            workerLabel: 'Worker: {{status}}',
            ramUsage: 'RAM: {{percent}}%',
            version: 'v0.1.0-demo',
          },
          settings: {
            title: 'Pengaturan',
            general: 'Umum',
            processing: 'Pemrosesan (Butuh Backend)',
            outputDir: '\ud83d\udd12 Folder Output',
            maxPdfPages: '\ud83d\udd12 Maks Halaman PDF',
            cpuThreads: '\ud83d\udd12 Thread CPU',
            reopenWelcome: 'Buka kembali Layar Sambutan',
            save: 'Simpan',
            close: 'Tutup',
            saved: 'Pengaturan disimpan',
            saveFailed: 'Gagal menyimpan pengaturan.',
            loadFailed: 'Gagal memuat pengaturan.',
            validationPages: 'Maks Halaman PDF minimal 1.',
            validationThreads: 'Thread CPU tidak boleh negatif.',
            autoHint: '0 = otomatis',
          },
          topbar: {
            logoAlt: 'Logo Scan2Text',
            brandAlt: 'Scan2Text',
            demoBadge: 'DEMO',
          },
          welcome: {
            title: 'Selamat datang di Scan2Text',
            bullet1: 'Bekerja sepenuhnya offline; file Anda tidak pernah meninggalkan PC ini.',
            bullet2: 'Tanpa akun, tanpa telemetri, tanpa isi dokumen atau nama file di log.',
            bullet3: 'File besar atau padat bisa memakan waktu beberapa menit; aplikasi tetap responsif.',
            bullet4: 'Output adalah Markdown sebaik mungkin — selalu periksa kembali angka-angka penting.',
            dontShowAgain: 'Jangan tampilkan lagi',
            close: 'Mulai',
          },
          feedback: {
            tooltip: 'Kirim masukan',
            title: 'Kirim Masukan',
            messageLabel: 'Masukan Anda',
            messagePlaceholder: 'Ceritakan pendapat Anda...',
            contactLabel: 'Email (opsional)',
            contactPlaceholder: 'anda@contoh.com',
            submit: 'Kirim',
            success: 'Masukan tersimpan!',
            pendingToast: 'Anda memiliki masukan tertunda.',
            pendingAction: 'Kirim sekarang',
            formUrl: 'https://placeholder.local/feedback',
          },
          downloader: {
            title: 'Mengunduh Mesin AI',
            description: 'Mohon tunggu sementara kami menyiapkan model AI offline...',
            progress: '{{downloaded}} dari {{total}}',
            cancel: 'Batal',
            restart: 'Mulai Ulang Unduhan',
            failed: 'Unduhan gagal atau dibatalkan.',
            verifying: 'Memverifikasi integritas file...',
          },
        },
      },
    },
    lng: 'en',
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  })
