import '@testing-library/jest-dom/vitest'
import { vi } from 'vitest'
import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'

vi.mock('sonner', () => ({
  Toaster: () => null,
  toast: {
    error: vi.fn(),
    success: vi.fn(),
    info: vi.fn(),
    warning: vi.fn(),
  },
}))

void i18next
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: {
          app: { title: 'Scan2Text' },
          panels: { dropZone: 'Drop Zone', queue: 'Queue', preview: 'Preview' },
          status: { ready: 'Ready' },
          actions: { toggleTheme: 'Toggle theme', toggleLanguage: 'Toggle language', langTooltipEn: 'Switch to Bahasa', langTooltipId: 'Switch to English', shareTooltip: 'Share app link' },
          dropzone: {
            hint: 'PNG · JPG · WEBP · PDF — max 50MB per file · max 10 files per batch',
            clickLabel: 'Click or drag files here',
            dropLabel: 'Drop files here',
            maxFilesWarning: 'Max 10 files per batch — extra files were skipped.',
          },
          errors: {
            unsupportedFileType: 'Unsupported file type. Allowed: PNG, JPG, JPEG, WEBP, PDF',
            fileTooLarge: 'File exceeds 50MB limit',
            uploadFailed: 'Upload failed',
            batchSkipped: '{{total}} files were skipped: {{unsupported}} unsupported type(s), {{tooLarge}} too large.',
            allInvalid: 'All selected files are unsupported or too large.',
            pdfTooComplex: 'PDF too complex for the current page limit. Raise the page limit in Settings and retry.',
            fileTooComplex: 'File too complex (max 20MB).',
          },
          preview: {
            empty: 'Select a job to preview',
            loading: 'Processing your file...',
            error: 'Processing failed. Please try again.',
            retry: 'Retry',
          },
          queue: {
            empty: 'No files in queue',
            emptyFriendly: ' Nothing here yet. Drop something tasty!',
            remove: 'Remove',
            retry: 'Retry',
            status: {
              pending: 'Pending',
              uploading: 'Uploading',
              processing: 'Processing',
              completed: 'Completed',
              failed: 'Failed',
            },
          },
          bottomBar: {
            workerLabel: 'Worker: {{status}}',
            ramUsage: 'RAM: {{percent}}%',
            version: 'v0.1.0-demo',
          },
          settings: {
            title: 'Settings',
            general: 'General',
            processing: 'Processing (Backend Required)',
            outputDir: '\ud83d\udd12 Output Directory',
            maxPdfPages: '\ud83d\udd12 Max PDF Pages',
            cpuThreads: '\ud83d\udd12 CPU Threads',
            reopenWelcome: 'Re-open Welcome Screen',
            save: 'Save',
            close: 'Close',
            saved: 'Settings saved',
            saveFailed: 'Failed to save settings.',
            loadFailed: 'Failed to load settings.',
            validationPages: 'Max PDF Pages must be at least 1.',
            validationThreads: 'CPU Threads cannot be negative.',
            autoHint: '0 = auto',
          },
          topbar: {
            logoAlt: 'Scan2Text logo',
            brandAlt: 'Scan2Text',
            demoBadge: 'DEMO',
          },
          welcome: {
            title: 'Welcome to Scan2Text',
            body: "Turn your scanned documents into editable text — no internet required. Quick heads-up: Files must be under 20MB (that's about 10-20 photos or a short PDF). PDFs can be up to 50 pages. We accept PNG, JPG, WEBP, and PDF. Ready? Drop your files below!",
            dontShowAgain: "Don't show this again",
             close: 'Get Started',
           },
           backend: {
             bootFailed: 'Backend failed to start. Check logs/ for details.',
           },
           feedback: {
             tooltip: 'Send feedback',
            title: 'Send Feedback',
            messageLabel: 'Your feedback',
            messagePlaceholder: 'Tell us what you think...',
            contactLabel: 'Email (optional)',
            contactPlaceholder: 'you@example.com',
            submit: 'Send',
            success: 'Feedback saved!',
            pendingToast: 'You have pending feedback to send.',
            pendingAction: 'Send now',
            formUrl: 'https://placeholder.local/feedback',
          },
          downloader: {
            title: 'Downloading AI Engine',
            description: 'Please wait while we prepare the offline AI model...',
            progress: '{{downloaded}} of {{total}}',
            progressUnknown: 'Waiting for download info…',
            cancel: 'Cancel',
            restart: 'Restart Download',
            retry: 'Retry Download',
            failed: 'Download failed or cancelled.',
            verifying: 'Verifying file integrity...',
            error: {
              network: 'Network connection failed. Please check your connection and try again.',
              sizeMismatch: 'Downloaded file size does not match the expected size.',
              diskFull: 'Not enough disk space to complete the download.',
              userCancelled: 'Download was cancelled.',
              versionJsonMissing: 'Model manifest not found. Restart download to fetch it.',
            },
            errorGeneric: 'Error: {{message}}',
          },
        },
      },
      id: {
        translation: {
          app: { title: 'Scan2Text' },
          panels: { dropZone: 'Zona Jatuh', queue: 'Antrian', preview: 'Pratinjau' },
          status: { ready: 'Siap' },
          actions: { toggleTheme: 'Ubah tema', toggleLanguage: 'Ubah bahasa', langTooltipEn: 'Beralih ke Bahasa Indonesia', langTooltipId: 'Beralih ke Bahasa Inggris', shareTooltip: 'Bagikan tautan aplikasi' },
          dropzone: {
            hint: 'PNG · JPG · WEBP · PDF — maks 50MB per file · maks 10 file per batch',
            clickLabel: 'Klik atau seret file ke sini',
            dropLabel: 'Lepaskan file di sini',
            maxFilesWarning: 'Maksimal 10 file per batch — file tambahan dilewati.',
          },
          errors: {
            unsupportedFileType: 'Tipe file tidak didukung. Yang didukung: PNG, JPG, JPEG, WEBP, PDF',
            fileTooLarge: 'Ukuran file melebihi batas 50MB',
            uploadFailed: 'Gagal mengunggah',
            batchSkipped: '{{total}} file dilewati: {{unsupported}} tipe tidak didukung, {{tooLarge}} terlalu besar.',
            allInvalid: 'Semua file yang dipilih tidak didukung atau terlalu besar.',
            pdfTooComplex: 'PDF terlalu kompleks untuk batas halaman saat ini. Naikkan batas halaman di Pengaturan lalu coba lagi.',
            fileTooComplex: 'File terlalu kompleks (maks 20MB).',
          },
          preview: {
            empty: 'Pilih pekerjaan untuk pratinjau',
            loading: 'Memproses file Anda...',
            error: 'Pemrosesan gagal. Silakan coba lagi.',
            retry: 'Coba Lagi',
          },
          queue: {
            empty: 'Tidak ada file dalam antrian',
            emptyFriendly: '🙈 Masih belum ada file tuh! Coba upload di atas!',
            remove: 'Hapus',
            retry: 'Ulangi',
            status: {
              pending: 'Menunggu',
              uploading: 'Mengunggah',
              processing: 'Memproses',
              completed: 'Selesai',
              failed: 'Gagal',
            },
          },
          bottomBar: {
            workerLabel: 'Worker: {{status}}',
            ramUsage: 'RAM: {{percent}}%',
            version: 'v0.1.0-demo',
          },
          settings: {
            title: 'Pengaturan',
            general: 'Umum',
            processing: 'Pemrosesan (Butuh Backend)',
            outputDir: '\ud83d\udd12 Folder Output',
            maxPdfPages: '\ud83d\udd12 Maks Halaman PDF',
            cpuThreads: '\ud83d\udd12 Thread CPU',
            reopenWelcome: 'Buka kembali Layar Sambutan',
            save: 'Simpan',
            close: 'Tutup',
            saved: 'Pengaturan disimpan',
            saveFailed: 'Gagal menyimpan pengaturan.',
            loadFailed: 'Gagal memuat pengaturan.',
            validationPages: 'Maks Halaman PDF minimal 1.',
            validationThreads: 'Thread CPU tidak boleh negatif.',
            autoHint: '0 = otomatis',
          },
          topbar: {
            logoAlt: 'Logo Scan2Text',
            brandAlt: 'Scan2Text',
            demoBadge: 'DEMO',
          },
          welcome: {
            title: 'Selamat datang di Scan2Text',
            body: 'Ubah dokumen hasil scan Anda menjadi teks yang bisa diedit — tanpa internet. Catatan cepat: File harus di bawah 20MB (sekitar 10-20 foto atau PDF pendek). PDF bisa sampai 50 halaman. Kami menerima PNG, JPG, WEBP, dan PDF. Siap? Jatuhkan file Anda di bawah!',
            dontShowAgain: 'Jangan tampilkan lagi',
            close: 'Mulai',
          },
          backend: {
            bootFailed: 'Backend gagal dimulai. Periksa logs/ untuk detail.',
          },
          feedback: {
            tooltip: 'Kirim masukan',
            title: 'Kirim Masukan',
            messageLabel: 'Masukan Anda',
            messagePlaceholder: 'Ceritakan pendapat Anda...',
            contactLabel: 'Email (opsional)',
            contactPlaceholder: 'anda@contoh.com',
            submit: 'Kirim',
            success: 'Masukan tersimpan!',
            pendingToast: 'Anda memiliki masukan tertunda.',
            pendingAction: 'Kirim sekarang',
            formUrl: 'https://placeholder.local/feedback',
          },
          downloader: {
            title: 'Mengunduh Mesin AI',
            description: 'Mohon tunggu sementara kami menyiapkan model AI offline...',
            progress: '{{downloaded}} dari {{total}}',
            progressUnknown: 'Menunggu informasi unduhan…',
            cancel: 'Batal',
            restart: 'Mulai Ulang Unduhan',
            retry: 'Coba Lagi Unduhan',
            failed: 'Unduhan gagal atau dibatalkan.',
            verifying: 'Memverifikasi integritas file...',
            error: {
              network: 'Koneksi jaringan gagal. Periksa koneksi Anda dan coba lagi.',
              sizeMismatch: 'Ukuran file yang diunduh tidak sesuai dengan ukuran yang diharapkan.',
              diskFull: 'Ruang disk tidak cukup untuk menyelesaikan unduhan.',
              userCancelled: 'Unduhan dibatalkan.',
              versionJsonMissing: 'Manifes model tidak ditemukan. Mulai ulang unduhan untuk mengambilnya.',
            },
            errorGeneric: 'Kesalahan: {{message}}',
          },
        },
      },
    },
    lng: 'en',
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  })
