import { IS_DEMO_MODE } from './demoMode'
import { buildApiUrl } from './apiBase'

export { IS_DEMO_MODE } from './demoMode'

interface DemoTaskState {
  status: string
  result_markdown?: string
  startTime: number
}

const demoTasks = new Map<string, DemoTaskState>()

function generateDemoMarkdown(file: File): string {
  if (file.type === 'application/pdf') {
    return `# Document OCR Result

## Page 1

This is a sample extracted text from the PDF document. The OCR engine has processed the scanned content and converted it into editable Markdown format.

### Key Findings

- First bullet point from the document
- Second bullet point with additional details
- Third bullet point summarizing the main conclusion

| Column A | Column B | Column C |
|----------|----------|----------|
| Value 1  | Value 2  | Value 3  |
| Value 4  | Value 5  | Value 6  |

---

*Generated by Scan2Text Demo Mode*`
  }

  return `# Image OCR Result

## Extracted Text

This is a sample extracted text from the image file. The OCR engine has processed the scanned content and converted it into editable Markdown format.

### Details

- Item one from the image
- Item two with more context
- Item three concluding the analysis`
}

export interface UploadResponse {
  task_id: string
}

export interface TaskStatusResponse {
  task_id: string
  status: string
  result_markdown?: string
  error?: string
}

export interface CompletedTaskStatusResponse {
  task_id: string
  status: 'completed'
  result_markdown: string
  error?: string
}

export interface FailedTaskStatusResponse {
  task_id: string
  status: 'failed'
  error?: string
}

export function isTaskCompleted(
  response: TaskStatusResponse
): response is CompletedTaskStatusResponse {
  return (
    response.status === 'completed' &&
    typeof response.result_markdown === 'string'
  )
}

export function isTaskFailed(
  response: TaskStatusResponse
): response is FailedTaskStatusResponse {
  return response.status === 'failed'
}

export async function getTaskStatus(taskId: string): Promise<TaskStatusResponse> {
  if (IS_DEMO_MODE) {
    const demoState = demoTasks.get(taskId)
    if (!demoState) {
      return { task_id: taskId, status: 'processing' }
    }

    const elapsed = Date.now() - demoState.startTime
    if (elapsed >= 2000 && demoState.result_markdown) {
      return { task_id: taskId, status: 'completed', result_markdown: demoState.result_markdown }
    }

    return { task_id: taskId, status: 'processing' }
  }

  const response = await fetch(buildApiUrl(`/status/${encodeURIComponent(taskId)}`))

  if (!response.ok) {
    throw new Error(`Status check failed: ${response.status} ${response.statusText}`)
  }

  return response.json() as Promise<TaskStatusResponse>
}

export interface PollOptions {
  maxAttempts: number
  intervalMs: number
}

export interface PollDeps {
  getStatus: (id: string) => Promise<TaskStatusResponse>
  delay: (ms: number) => Promise<void>
}

export async function pollTaskStatus(
  taskId: string,
  options: PollOptions,
  deps: PollDeps
): Promise<TaskStatusResponse> {
  for (let attempt = 0; attempt < options.maxAttempts; attempt++) {
    const response = await deps.getStatus(taskId)
    if (isTaskCompleted(response) || isTaskFailed(response)) {
      return response
    }
    if (attempt < options.maxAttempts - 1) {
      await deps.delay(options.intervalMs)
    }
  }
  throw new Error('Polling timeout: max attempts reached')
}

export const defaultDelay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

export async function uploadFile(file: File): Promise<UploadResponse> {
  if (IS_DEMO_MODE) {
    await new Promise(resolve => setTimeout(resolve, 500))
    const taskId = 'demo-' + Date.now()
    const markdown = generateDemoMarkdown(file)
    demoTasks.set(taskId, {
      status: 'processing',
      result_markdown: markdown,
      startTime: Date.now(),
    })
    return { task_id: taskId }
  }

  const formData = new FormData()
  formData.append('files', file, file.name)
  const response = await fetch(buildApiUrl('/process'), {
    method: 'POST',
    body: formData,
  })
  if (!response.ok) {
    throw new Error(`Upload failed: ${response.status} ${response.statusText}`)
  }
  return response.json() as Promise<UploadResponse>
}
